#端口号
server:
  #port: 8003
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 #默认是2M,可以修改为100M或者-1

#服务名称,以后微服务注册可以使用
spring:
  profiles:
    active: dev  #dev(development开发环境)、test(测试环境)、prod(Production生产环境)
  application:
    name: service-user
  datasource:                                         # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/imooc-news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password:
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:SS
    time-zone: GMT+8
    ############################################################
    #
    # mybatis 配置
    #
    ############################################################
mybatis:
      type-aliases-package: com.mzj.pojo          # 所有POJO类所在包路径
      mapper-locations: classpath:mapper/*.xml      # mapper映射文件
    ############################################################
    #
    # mybatis mapper 配置
    #
    ############################################################
    # 通用 Mapper 配置
mapper:
      mappers: com.mzj.my.mapper.MyMapper
      not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
      identity: MYSQL
    # 分页插件配置
pagehelper:
      helperDialect: mysql
      supportMethodsArguments: true
